# ruff: noqa: E501


def dashboard_html() -> str:
    return r"""<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="icon" href="data:,"><title>EagleEye AI QA</title>
  <style>
    :root{color-scheme:dark;--bg:#0b0e13;--surface:#121720;--surface2:#181e29;--line:#2b3442;--ink:#edf1f7;--muted:#9ba7b8;--primary:#21b8a6;--primary2:#159282;--blue:#68a6ff;--green:#48d597;--amber:#f3bd52;--red:#ff7373;--radius:7px}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}button,input,select,textarea{font:inherit}button{cursor:pointer}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid var(--blue);outline-offset:2px}
    .app{min-height:100vh;display:grid;grid-template-rows:58px 1fr}.topbar{position:sticky;top:0;z-index:10;display:flex;align-items:center;gap:18px;padding:0 22px;border-bottom:1px solid var(--line);background:#0e1219ee;backdrop-filter:blur(12px)}.brand{font-weight:800;font-size:16px}.brand b{color:var(--primary)}.env{padding:3px 7px;border:1px solid #31564f;border-radius:999px;color:var(--green);font-size:11px}.health{margin-left:auto;display:flex;align-items:center;gap:7px;color:var(--muted);font-size:12px}.dot{width:7px;height:7px;border-radius:50%;background:var(--amber)}.dot.on{background:var(--green);box-shadow:0 0 0 3px #48d5971c}
    .shell{display:grid;grid-template-columns:210px minmax(0,1fr)}nav{padding:18px 12px;border-right:1px solid var(--line);background:#0e1219}.nav-label{padding:8px 10px;color:#6f7c8e;font-size:10px;text-transform:uppercase}.nav-btn,.nav-link{width:100%;display:flex;align-items:center;gap:9px;margin:2px 0;padding:9px 10px;border:0;border-radius:6px;background:transparent;color:var(--muted);text-align:left;text-decoration:none}.nav-btn:hover,.nav-link:hover{background:var(--surface2);color:var(--ink)}.nav-btn.active{background:#18312f;color:#eafffb}.nav-icon{width:20px;text-align:center}.nav-meta{margin:22px 10px 0;padding-top:15px;border-top:1px solid var(--line);color:var(--muted);font-size:11px}.nav-meta strong{display:block;margin-top:4px;color:var(--ink)}
    main{min-width:0;padding:24px}.page{display:none;max-width:1280px;margin:0 auto}.page.active{display:block}.page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:20px}.page-head h1{margin:0 0 4px;font-size:22px}.page-head p{margin:0;color:var(--muted)}.layout{display:grid;grid-template-columns:minmax(420px,.85fr) minmax(420px,1.15fr);gap:18px}.panel{border:1px solid var(--line);border-radius:var(--radius);background:var(--surface)}.panel-head{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;border-bottom:1px solid var(--line)}.panel-head h2{margin:0;font-size:14px}.panel-body{padding:16px}
    form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}label{display:grid;gap:5px;color:var(--muted);font-size:11px}input,select,textarea{width:100%;padding:9px 10px;border:1px solid var(--line);border-radius:6px;background:#0d1118;color:var(--ink)}textarea{min-height:82px;resize:vertical}.wide{grid-column:1/-1}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:4px}.btn{border:1px solid transparent;border-radius:6px;padding:9px 13px;background:var(--primary2);color:white;font-weight:700}.btn:hover{background:var(--primary)}.btn:disabled{cursor:wait;opacity:.55}.btn.secondary{border-color:var(--line);background:var(--surface2);color:var(--ink)}.btn.ghost{background:transparent;color:var(--muted)}
    .presets{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:14px}.chip{padding:5px 9px;border:1px solid var(--line);border-radius:999px;background:transparent;color:var(--muted);font-size:11px}.chip:hover{border-color:var(--primary);color:var(--ink)}
    .empty{display:grid;place-items:center;min-height:330px;padding:30px;text-align:center;color:var(--muted)}.empty b{display:block;margin-bottom:5px;color:var(--ink)}.result-wrap{padding:16px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:14px}.metric{padding:12px;border:1px solid var(--line);border-radius:6px;background:#0d1118}.metric small{display:block;color:var(--muted)}.metric strong{display:block;margin-top:3px;font-size:22px}.metric.good strong{color:var(--green)}.metric.warn strong{color:var(--amber)}.metric.bad strong{color:var(--red)}.section-title{margin:17px 0 8px;font-size:12px}.list{margin:0;padding-left:19px;color:#ced6e1}.list li{margin:4px 0}.badge{display:inline-flex;align-items:center;padding:3px 7px;border-radius:999px;font-size:10px;font-weight:800}.badge.PASS{background:#173c31;color:var(--green)}.badge.PASS_WITH_WARNING,.badge.WARNING{background:#463719;color:var(--amber)}.badge.FAIL{background:#482323;color:var(--red)}
    .case-input{min-height:430px;font:12px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}.helper{display:flex;justify-content:space-between;margin:6px 0 0;color:var(--muted);font-size:10px}.issues{display:grid;gap:8px}.issue{display:grid;grid-template-columns:74px 1fr;gap:10px;padding:11px;border:1px solid var(--line);border-left:3px solid var(--amber);border-radius:5px;background:#0d1118}.issue.critical,.issue.high{border-left-color:var(--red)}.issue.low,.issue.info{border-left-color:var(--blue)}.issue-code{font:10px/1.3 ui-monospace,monospace;color:var(--muted);word-break:break-word}.issue strong{font-size:12px}.issue p{margin:3px 0 0;color:var(--muted);font-size:11px}.case-table{width:100%;border-collapse:collapse;font-size:12px}.case-table th,.case-table td{padding:9px;border-bottom:1px solid var(--line);text-align:left}.case-table th{color:var(--muted);font-weight:500}.case-table td:nth-child(3){text-align:right}.toast{position:fixed;right:18px;bottom:18px;z-index:20;padding:10px 13px;border:1px solid #30685e;border-radius:6px;background:#132a27;color:#dffff9;box-shadow:0 12px 30px #0008;opacity:0;transform:translateY(8px);transition:.2s;pointer-events:none}.toast.show{opacity:1;transform:none}
    .providers{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px}.provider{padding:12px;border:1px solid var(--line);border-radius:6px;background:#0d1118}.provider-top{display:flex;justify-content:space-between;gap:8px}.provider small{display:block;margin-top:4px;color:var(--muted)}.model-card{border-left:3px solid var(--blue)}.model-card.recommended{border-left-color:var(--green);background:#10221d}.model-meta{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.model-note{margin:7px 0 0;color:var(--muted);font-size:11px}.model-source{display:inline-block;margin-top:8px;font-size:10px}.disclaimer{margin-bottom:12px;padding:10px;border:1px solid #5f512b;background:#262113;color:#ffe09b;font-size:11px}
    @media(max-width:980px){.shell{grid-template-columns:68px 1fr}.nav-btn{justify-content:center}.nav-text,.nav-label,.nav-meta{display:none}.layout{grid-template-columns:1fr}}
    @media(max-width:620px){.topbar{padding:0 12px}.env{display:none}.shell{display:block}nav{position:fixed;bottom:0;left:0;right:0;z-index:15;display:flex;padding:6px;border:0;border-top:1px solid var(--line)}.nav-btn{margin:0}.nav-text{display:none}main{padding:16px 12px 78px}.page-head{display:block}.page-head .actions{margin-top:10px}form{grid-template-columns:1fr}.wide{grid-column:auto}.metrics{grid-template-columns:1fr 1fr}.metrics .metric:last-child{grid-column:1/-1}.issue{grid-template-columns:1fr}.case-input{min-height:340px}}
  </style>
</head>
<body><div class="app">
  <header class="topbar"><div class="brand"><b>◉</b> EagleEye QA</div><span class="env">LOCAL SAFE</span><div class="health"><span id="health-dot" class="dot"></span><span id="health-text">接続確認中</span></div></header>
  <div class="shell"><nav aria-label="メインナビゲーション">
    <div class="nav-label">QA workspace</div>
    <button class="nav-btn active" data-page="strategy" aria-label="テスト戦略"><span class="nav-icon">⌁</span><span class="nav-text">テスト戦略</span></button>
    <button class="nav-btn" data-page="checker" aria-label="ケース自動チェック"><span class="nav-icon">✓</span><span class="nav-text">ケース自動チェック</span></button>
    <button class="nav-btn" data-page="providers" aria-label="AI接続状態"><span class="nav-icon">◇</span><span class="nav-text">AI接続状態</span></button>
    <a class="nav-link" href="/guided" aria-label="誘導シナリオQA"><span class="nav-icon">◎</span><span class="nav-text">誘導シナリオQA</span></a>
    <div class="nav-meta">安全ポリシー<strong>AIは必須テストを削除不可</strong></div>
  </nav><main>
    <section id="strategy" class="page active">
      <div class="page-head"><div><h1>テスト戦略</h1><p>変更内容とリスクから、実行すべきテストを最短で決定します。</p></div></div>
      <div class="layout"><section class="panel"><div class="panel-head"><h2>プロファイル設定</h2><button class="btn ghost" id="reset-profile" type="button">リセット</button></div><div class="panel-body">
        <div class="presets"><button class="chip" data-preset="feature">機能開発</button><button class="chip" data-preset="release">リリース前</button><button class="chip" data-preset="production">本番確認</button></div>
        <form id="profile-form">
          <label>プロジェクトID<input name="projectId" value="eagleeye-demo" required></label>
          <label>開発段階<select name="developmentStage"><option value="development">機能開発</option><option value="integration">結合</option><option value="system_test">システムテスト</option><option value="release">リリース前</option><option value="production">本番</option><option value="maintenance">保守</option></select></label>
          <label>サービス種別<select name="serviceType"><option value="web">Web</option><option value="ecommerce">EC・予約</option><option value="business">業務</option><option value="api">API</option><option value="batch">Batch</option><option value="ai_agent" selected>AI Agent</option><option value="legacy_desktop">Legacy Desktop</option></select></label>
          <label>事業影響<select name="business_impact"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></label>
          <label>データ機密性<select name="data_sensitivity"><option>low</option><option>medium</option><option selected>high</option><option>critical</option></select></label>
          <label>変更複雑度<select name="change_complexity"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></label>
          <label>ユーザー影響<select name="user_impact"><option>low</option><option>medium</option><option selected>high</option><option>critical</option></select></label>
          <label>復旧可能性<select name="recoverability"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></label>
          <label class="wide">変更ファイル（1行1件）<textarea name="changedFiles">app/providers.py
app/mcp_server.py</textarea></label>
          <div class="wide actions"><button class="btn" type="submit">戦略を生成</button></div>
        </form>
      </div></section><section class="panel"><div class="panel-head"><h2>推奨結果</h2><button class="btn ghost" id="copy-strategy" type="button" disabled>JSONをコピー</button></div><div id="profile-result" class="empty"><div><b>まだ戦略は生成されていません</b>左の入力を確認して「戦略を生成」を押してください。</div></div></section></div>
    </section>

    <section id="checker" class="page">
      <div class="page-head"><div><h1>テストケース自動チェック</h1><p>曖昧さ、flaky要因、秘密値、重複、カバレッジ不足を実行前に検出します。</p></div><div class="actions"><button class="btn secondary" id="load-bad-sample">問題例</button><button class="btn secondary" id="load-good-sample">良好例</button></div></div>
      <div class="layout"><section class="panel"><div class="panel-head"><h2>テストケース JSON</h2><span id="case-count" class="badge WARNING">0 cases</span></div><div class="panel-body">
        <label>プロジェクトID<input id="check-project" value="eagleeye-demo"></label>
        <label style="margin-top:10px">必須テスト種別（カンマ区切り）<input id="required-types" value="e2e,security"></label>
        <label style="margin-top:10px">ケース配列<textarea id="case-json" class="case-input" spellcheck="false"></textarea></label>
        <div class="helper"><span>最大500ケース。秘密値は貼り付けないでください。</span><span id="json-state">入力待ち</span></div>
        <div class="actions"><button class="btn secondary" id="format-json">整形</button><button class="btn" id="run-check">自動チェック</button></div>
      </div></section><section class="panel"><div class="panel-head"><h2>健全性レポート</h2><button class="btn ghost" id="copy-check" disabled>JSONをコピー</button></div><div id="check-result" class="empty"><div><b>テストケースを貼り付けてください</b>良好例・問題例からすぐに動作を試せます。</div></div></section></div>
    </section>

    <section id="providers" class="page">
      <div class="page-head"><div><h1>AI接続状態とモデル選定</h1><p>資格情報を表示せず、接続状態とQA用途別の推奨モデルを確認します。</p></div></div>
      <section class="panel"><div class="panel-head"><h2>プロバイダー</h2></div><div class="panel-body"><div id="provider-list" class="providers">読み込み中…</div></div></section>
      <section class="panel" style="margin-top:18px"><div class="panel-head"><h2>限定自己修復</h2></div><div class="panel-body"><div id="repair-status" class="providers">読み込み中…</div></div></section>
      <section class="panel" style="margin-top:18px"><div class="panel-head"><h2>用途別の推奨モデル</h2><select id="model-workload" style="width:auto"><option value="">すべて</option><option value="release_assurance">リリース・根本原因</option><option value="balanced" selected>日常QA・バランス</option><option value="high_volume">大量一次チェック</option><option value="local_private">ローカル・機密優先</option></select></div><div class="panel-body"><div id="model-disclaimer" class="disclaimer">読み込み中…</div><div id="model-list" class="providers"></div></div></section>
    </section>
  </main></div></div><div id="toast" class="toast" role="status"></div>
<script>
  const $=selector=>document.querySelector(selector); let lastStrategy=null,lastCheck=null;
  const goodSample=[{id:'TC-001',title:'有効な利用者が登録を完了できる',type:'e2e',steps:['登録画面を開く','有効なメールを入力して登録ボタンを押す'],expectedResults:['完了画面に Registration completed が表示される'],assertions:["getByRole('heading',{name:'Registration completed'}) is visible"],tags:['happy-path'],priority:'high',criticalFlow:true}];
  const badSample=[{id:'TC-002',title:'ログイン確認',type:'e2e',steps:['password=actualSecret123 を入力','sleep 5秒','//div[3]/button を押す'],expectedResults:['正常'],assertions:[],tags:['happy-path'],priority:'medium',criticalFlow:true,retryCount:3}];
  function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
  function esc(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function activatePage(name,updateHash=true){const safe=['strategy','checker','providers'].includes(name)?name:'strategy';document.querySelectorAll('.nav-btn,.page').forEach(el=>el.classList.remove('active'));document.querySelector(`[data-page="${safe}"]`).classList.add('active');$('#'+safe).classList.add('active');if(updateHash)history.pushState(null,'','#'+safe)}document.querySelectorAll('.nav-btn').forEach(button=>button.addEventListener('click',()=>activatePage(button.dataset.page)));window.addEventListener('hashchange',()=>activatePage(location.hash.slice(1),false));activatePage(location.hash.slice(1),false);
  async function health(){try{const r=await fetch('/health');if(!r.ok)throw Error();$('#health-dot').classList.add('on');$('#health-text').textContent='API・MCP 稼働中'}catch{$('#health-text').textContent='接続エラー'}}health();
  const profileForm=$('#profile-form');
  document.querySelectorAll('[data-preset]').forEach(button=>button.addEventListener('click',()=>{const p=button.dataset.preset;profileForm.developmentStage.value=p==='feature'?'development':p;profileForm.business_impact.value=p==='release'?'high':'medium';profileForm.data_sensitivity.value=p==='production'?'critical':'high';toast('プリセットを適用しました')}));
  $('#reset-profile').addEventListener('click',()=>{profileForm.reset();lastStrategy=null;$('#copy-strategy').disabled=true;$('#profile-result').className='empty';$('#profile-result').innerHTML='<div><b>入力をリセットしました</b>変更内容に合わせて再設定してください。</div>'});
  profileForm.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent='分析中…';const form=new FormData(event.target);const risk=Object.fromEntries(['business_impact','data_sensitivity','change_complexity','user_impact','recoverability'].map(key=>[key,form.get(key)]));const body={projectId:form.get('projectId'),developmentStage:form.get('developmentStage'),serviceType:form.get('serviceType'),environment:'local',production:form.get('developmentStage')==='production',changedFiles:String(form.get('changedFiles')).split(/\r?\n/).map(x=>x.trim()).filter(Boolean),risk,aiEnabled:true};try{const response=await fetch('/api/v1/test-profiles/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.detail||'生成に失敗しました');lastStrategy=data;renderStrategy(data);$('#copy-strategy').disabled=false;toast('テスト戦略を生成しました')}catch(error){renderError('#profile-result',error.message)}finally{button.disabled=false;button.textContent='戦略を生成'}});
  function renderStrategy(data){const cls=data.riskScore>=70?'bad':data.riskScore>=40?'warn':'good';$('#profile-result').className='result-wrap';$('#profile-result').innerHTML=`<div class="metrics"><div class="metric ${cls}"><small>リスク</small><strong>${data.riskScore}</strong></div><div class="metric"><small>推奨モード</small><strong style="font-size:15px">${esc(data.recommendedMode.toUpperCase())}</strong></div><div class="metric"><small>人間承認</small><strong style="font-size:15px">${data.humanApprovalRequired?'必要':'通常実行可'}</strong></div></div><div class="section-title">選定理由</div><ul class="list">${data.reasons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="section-title">必須テスト (${data.requiredTests.length})</div><div>${data.requiredTests.map(x=>`<span class="chip">${esc(x)}</span>`).join(' ')}</div><div class="section-title">制約</div><ul class="list">${data.restrictions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;if(innerWidth<=620)$('#profile-result').scrollIntoView({behavior:'smooth',block:'start'})}
  $('#copy-strategy').addEventListener('click',()=>copy(lastStrategy));
  const caseInput=$('#case-json');function loadSample(sample,required='e2e',announce=true){caseInput.value=JSON.stringify(sample,null,2);$('#required-types').value=required;updateCaseState();lastCheck=null;$('#copy-check').disabled=true;if(announce){$('#check-result').className='empty';$('#check-result').innerHTML='<div><b>入力を更新しました</b>「自動チェック」を押して新しい結果を確認してください。</div>';caseInput.focus()}}$('#load-good-sample').addEventListener('click',()=>loadSample(goodSample,'e2e'));$('#load-bad-sample').addEventListener('click',()=>loadSample(badSample,'e2e,security'));loadSample(goodSample,'e2e',false);
  function updateCaseState(){try{const data=JSON.parse(caseInput.value);const count=Array.isArray(data)?data.length:0;$('#case-count').textContent=`${count} cases`;$('#json-state').textContent=Array.isArray(data)?'JSON valid':'配列が必要';$('#json-state').style.color=Array.isArray(data)?'var(--green)':'var(--red)'}catch{$('#case-count').textContent='0 cases';$('#json-state').textContent='JSON error';$('#json-state').style.color='var(--red)'}}function markCheckStale(){updateCaseState();if(lastCheck){lastCheck=null;$('#copy-check').disabled=true;$('#check-result').className='empty';$('#check-result').innerHTML='<div><b>入力が変更されました</b>再度「自動チェック」を実行してください。</div>'}}caseInput.addEventListener('input',markCheckStale);$('#required-types').addEventListener('input',markCheckStale);
  $('#format-json').addEventListener('click',()=>{try{caseInput.value=JSON.stringify(JSON.parse(caseInput.value),null,2);updateCaseState();toast('JSONを整形しました')}catch{toast('JSON形式を確認してください')}});
  $('#run-check').addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;button.textContent='検査中…';try{const cases=JSON.parse(caseInput.value);if(!Array.isArray(cases))throw Error('ケースはJSON配列で入力してください');const requiredTypes=$('#required-types').value.split(',').map(x=>x.trim()).filter(Boolean);const response=await fetch('/api/v1/test-cases/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:$('#check-project').value,cases,requiredTestTypes:requiredTypes})});const data=await response.json();if(!response.ok)throw Error(Array.isArray(data.detail)?data.detail.map(x=>x.msg).join(', '):data.detail||'検査に失敗しました');lastCheck=data;renderCheck(data);$('#copy-check').disabled=false;toast(`${cases.length}ケースを検査しました`)}catch(error){renderError('#check-result',error.message)}finally{button.disabled=false;button.textContent='自動チェック'}});
  function renderCheck(data){const cls=data.decision==='PASS'?'good':data.decision==='FAIL'?'bad':'warn';$('#check-result').className='result-wrap';const issueHtml=data.issues.length?data.issues.map(i=>`<div class="issue ${i.severity}"><div class="issue-code">${esc(i.severity)}<br>${esc(i.code)}</div><div><strong>${esc(i.message)}</strong><p>${esc(i.suggestion)}${i.testCaseIds.length?' · '+esc(i.testCaseIds.join(', ')):''}</p></div></div>`).join(''):'<div class="empty" style="min-height:100px"><div><b>問題は見つかりませんでした</b>実行可能な品質です。</div></div>';$('#check-result').innerHTML=`<div class="metrics"><div class="metric ${cls}"><small>健全性スコア</small><strong>${data.score}</strong></div><div class="metric"><small>判定</small><strong style="font-size:14px"><span class="badge ${data.decision}">${data.decision}</span></strong></div><div class="metric"><small>検出件数</small><strong>${data.issues.length}</strong></div></div><div class="section-title">ケース別結果</div><table class="case-table"><thead><tr><th>ケース</th><th>状態</th><th>Score</th></tr></thead><tbody>${data.cases.map(c=>`<tr><td>${esc(c.id)} · ${esc(c.title)}</td><td><span class="badge ${c.status}">${c.status}</span></td><td>${c.score}</td></tr>`).join('')}</tbody></table><div class="section-title">検出事項</div><div class="issues">${issueHtml}</div>`;if(innerWidth<=620)$('#check-result').scrollIntoView({behavior:'smooth',block:'start'})}
  $('#copy-check').addEventListener('click',()=>copy(lastCheck));async function copy(value){if(!value)return;await navigator.clipboard.writeText(JSON.stringify(value,null,2));toast('JSONをコピーしました')}
  function renderError(selector,message){const el=$(selector);el.className='empty';el.innerHTML=`<div><b style="color:var(--red)">処理できませんでした</b>${esc(message)}</div>`}
  async function loadProviders(){const response=await fetch('/api/v1/ai/providers');const items=await response.json();if(!response.ok)throw Error(items.detail||'接続状態を取得できません');$('#provider-list').innerHTML=items.map(item=>{const codex=item.provider.id==='codex-agent';const action=codex?(item.connected?`<div class="actions"><button class="btn secondary" data-auth-refresh="codex-agent">状態を再確認</button><button class="btn ghost" data-auth-disconnect="codex-agent">ログアウト</button></div>`:`<div class="actions"><button class="btn" data-auth-connect="codex-agent">ChatGPTで接続</button></div>`):'';return `<div class="provider"><div class="provider-top"><strong>${esc(item.provider.name)}</strong><span class="badge ${item.connected?'PASS':'WARNING'}">${item.connected?'CONNECTED':item.configured?'READY':'SETUP'}</span></div><small>${esc(item.provider.authModes.join(' / '))}</small><p class="model-note">${esc(item.provider.notes)}</p>${action}</div>`}).join('');document.querySelectorAll('[data-auth-connect]').forEach(button=>button.addEventListener('click',()=>connectCodex(button)));document.querySelectorAll('[data-auth-refresh]').forEach(button=>button.addEventListener('click',()=>loadProviders().then(()=>toast('接続状態を更新しました'))));document.querySelectorAll('[data-auth-disconnect]').forEach(button=>button.addEventListener('click',()=>disconnectCodex(button)))}
  async function connectCodex(button){button.disabled=true;button.textContent='認証準備中…';try{const response=await fetch('/api/v1/auth/providers/codex-agent/start',{method:'POST'});const data=await response.json();if(!response.ok)throw Error(data.detail||'ChatGPT認証を開始できません');const link=document.createElement('a');link.href=data.authorizationUrl;link.target='_blank';link.rel='noopener noreferrer';link.click();toast('ブラウザーでChatGPT認証を完了してください');setTimeout(()=>loadProviders().catch(()=>undefined),5000)}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='ChatGPTで接続'}}
  async function disconnectCodex(button){if(!confirm('CodexのChatGPTログインを解除しますか？'))return;button.disabled=true;try{const response=await fetch('/api/v1/auth/providers/codex-agent',{method:'DELETE'});const data=await response.json();if(!response.ok)throw Error(data.detail||'ログアウトできません');toast('ChatGPTログインを解除しました');await loadProviders()}catch(error){toast(error.message)}finally{button.disabled=false}}loadProviders().catch(error=>$('#provider-list').textContent=error.message);
  async function loadRepairStatus(){const response=await fetch('/api/v1/self-repair/status');const data=await response.json();if(!response.ok)throw Error(data.detail||'自己修復状態を取得できません');const capability=data.capabilities.find(item=>item.automaticApplyAllowed);const model=capability?`${capability.provider} / ${capability.models.join(', ')}`:'適用許可モデルなし';$('#repair-status').innerHTML=`<div class="provider model-card ${data.enabled?'recommended':''}"><div class="provider-top"><strong>Bounded repair</strong><span class="badge ${data.enabled?'PASS':'WARNING'}">${data.enabled?'ENABLED':'DISABLED'}</span></div><small>${esc(model)}</small><p class="model-note">ローカル・非本番・clean Git・fresh one-use評価証明・明示applyを全て要求します。</p></div><div class="provider"><div class="provider-top"><strong>変更上限</strong><span class="badge PASS">FAIL CLOSED</span></div><small>${data.limits.maxFiles} files / ${data.limits.maxChangedLines} lines / ${data.limits.maxAttempts} attempts</small><p class="model-note">検証失敗時はcheckpointへ戻し、秘密値・認証・依存関係・物理回路は自動変更しません。</p></div>`}loadRepairStatus().catch(error=>$('#repair-status').textContent=error.message);
  async function loadModels(){const workload=$('#model-workload').value;const response=await fetch('/api/v1/ai/model-recommendations'+(workload?'?workload='+encodeURIComponent(workload):''));const data=await response.json();if(!response.ok)throw Error(data.detail||'モデル情報を取得できません');$('#model-disclaimer').textContent=`${data.disclaimer} · 確認日 ${data.verifiedAt}`;$('#model-list').innerHTML=data.recommendations.map(item=>{const recommended=item.providerId===data.defaultProviderId&&item.model===data.defaultModel;return `<div class="provider model-card ${recommended?'recommended':''}"><div class="provider-top"><strong>${esc(item.model)}</strong>${recommended?'<span class="badge PASS">DEFAULT</span>':''}</div><small>${esc(item.providerId)}</small><div class="model-meta"><span class="chip">${esc(item.workload)}</span><span class="chip">${esc(item.stability)}</span><span class="chip">cost ${esc(item.costTier)}</span></div><p class="model-note">${esc(item.why)}</p>${item.minimumHardware?`<p class="model-note">必要環境: ${esc(item.minimumHardware)}</p>`:''}<a class="model-source" href="${esc(item.sourceUrl)}" target="_blank" rel="noreferrer">公式情報</a></div>`}).join('')||'<div class="empty" style="min-height:100px">該当する推奨はありません。</div>'}$('#model-workload').addEventListener('change',()=>loadModels().catch(error=>$('#model-list').textContent=error.message));loadModels().catch(error=>$('#model-list').textContent=error.message);
</script></body></html>"""
